#!/bin/bash

grep -s 'Solution:' -r . --include=*.solution | awk '{print $3}' | sort | uniq > .mc
grep -s 'Mission:' -r . --include=*.mission | awk '{print $2}' | sort | uniq > .mo

echo ''
echo '=================='
echo 'Completed Missions'
echo '=================='

cat .mc

echo ''
echo '============='
echo 'Open Missions'
echo '============='

grep -v -f .mc .mo

echo ''

