#!/bin/bash

source ./env

./.connection
if [ $? -ne 0 ]; then
  echo "Can't verify connection to the TRIX target server!"
  echo "Make sure, that you've set TRIX server address in $TARGET variable"
  exit 1
fi

if [ $# -ge 2 ]; then

  # handle input parameters
  silent=0
  if [ $# -ge 3 ]; then
    if [ $1 == '--silent' ]; then
      silent=1
      mission=$2
      key=$3
    fi
  else
    mission=$1
    key=$2
  fi

  solution=$mission'-'$key'.solution'
  link=$TARGET`./.path $mission.mission`$solution
  echo $link >> .attempts

  if [[ `curl -Is -w '%{http_code}' -o /dev/null $link` == 200 ]]; then

    echo $link >> .solutions
    wget --quiet -N $link

    if [ -f ./$solution ]; then
        chmod +x ./$solution
        ./$solution

       if [ $silent -eq 0 ]; then
         echo '________________________________________'
         echo ' - '$mission' - ' 
         echo 'Mission Success!!!'
         echo 'Score: +'`cat ./$solution | grep 'Solution: ' | cut -d ' ' -f 4 | tr -d '\n' | wc -c | tr -d ' '`
         cat ./$solution | grep 'Badge: ' | sed 's/#/!!!/g'
       fi
       if [ $REPORT -eq 1 ]; then
         curl -s $TARGET'../htbin/leader/report.py?login='$LOGIN'&score='`./score` > /dev/null
       fi
    fi

  else
    echo ''
    echo '>>> Wrong Solution! <<<'
    echo ''

    if [ ! -f $mission.mission ]; then
      echo "Be aware, agent! It looks like you've been framed - there is no mission named ["$mission"]"
      echo 'run ./status to see the list of available open missions'
      echo 'and then find [mission-name].mission with mission details'
    else
      echo 'Be careful, agent! Your solution key ('$key') seems to be wrong'
      echo 'the rival corporations are monitoring all failed attempts,'
      echo 'and your location could be traced!'
    fi

  fi

else
  echo 'You have to provide mission name and solution key as parameters'
  echo ''
  echo 'Usage: ./solve [mission-name] [solution-key]'
  echo ''
  echo 'Example: ./solve test-mission test-key'

fi

