#!/bin/bash

source ./target

./.connection
if [ $? -ne 0 ]; then
  echo "Can't verify connection to the TRIX target server!"
  echo "Make sure, that you've set TRIX server address in $TARGET variable"
  exit 1
fi

if [ $# -eq 2  ]; then

  solution=$1'-'$2'.solution'
  link=$TARGET`./.path $1.mission`$solution
  echo $link >> .attempts

  if [[ `curl -Is -w '%{http_code}' -o /dev/null $link` == 200 ]]; then

    echo $link >> .solutions
    wget --quiet -N $link

    chmod +x ./$solution
    ./$solution

  else
    echo ''
    echo '>>> Wrong Solution! <<<'
    echo ''

    if [ ! -f $1.mission ]; then
      echo "Be aware, agent! It looks like you've been framed - there is no mission named ["$1"]"
      echo 'run ./status to see the list of available open missions'
      echo 'and then find [mission-name].mission with mission details'
    else
      echo 'Be careful, agent! Your solution key ('$2') seems to be wrong'
      echo 'the rival corporations are monitoring all failed attempts,'
      echo 'and your location could be traced!'
    fi

  fi

else
  echo 'You have to provide mission name and solution key as parameters'
  echo ''
  echo 'Usage: ./solve [mission-name] [solution-key]'
  echo ''
  echo 'Example: ./solve test-mission test-key'

fi

