#!/bin/bash

clear

CLEAR='\E[0m'
UNDERLINE='\033[4m'

RED='\e[0;31m'
YELLOW='\e[1;33m'
CYAN='\e[0;36m'
LGREEN='\e[1;32m'

echo -en $LGREEN
echo ''
echo '                 T R I X'
echo -en $YELLOW
echo ''
echo '        @   @  @   @  @@@  @   @ '
echo '        @   @  @@  @   @    @ @  '
echo '        @   @  @ @ @   @     @   '
echo '        @   @  @  @@   @    @ @  '
echo '        @@@@@  @   @  @@@  @   @ '
echo ''
echo -en $LGREEN
echo '                Version 3.1'

echo -en $RED
echo -e 'Loading kernel...'
echo -ne $CLEAR
echo ''

export TRIX_HOME=`pwd`
export TRIX_BIN=$TRIX_HOME
export PATH=`pwd`:`pwd`/bin/:$PATH

bash --init-file trix.ini

