#!/bin/bash

# upgrade trix tools

source ./target

wget -N $TARGET/home/.connection
wget -N $TARGET/home/.level
wget -N $TARGET/home/.levelup
wget -N $TARGET/home/.path
wget -N $TARGET/home/badges
wget -N $TARGET/home/faq.txt
wget -N $TARGET/home/missions
wget -N $TARGET/home/readme.txt
wget -N $TARGET/home/score
wget -N $TARGET/home/setup
wget -N $TARGET/home/solve
wget -N $TARGET/home/status
wget -N $TARGET/home/target

bash setup

echo 'System Updated'
echo ''
echo 'Don't forget to check the ./target file and set the correct target server'
echo ''

