#!/bin/bash

if [ -f ./system/server.pid ]; then
  echo -n 'Shutting down the server...'
  cd ./system
  ./kill-server
  cd ..
  echo 'OK'
fi


# clean home folder
cd home
./clean
cd ..

# clean system folder
echo -n 'Cleaning system...' 

rm -f system/server.pid
rm -f system/server.log
rm -f system/trix/trix.tar
echo 'OK'

