#!/bin/bash

if [ -f ./system/server.pid ]; then
  echo -n 'Shutting down the server...'
  cd ./system
  ./kill-server
  cd ..
  echo 'OK'
fi

# clean output folder
echo -n 'Cleaning output directory...'
rm -rf ./out
echo 'OK'

# clean system folder
echo -n 'Cleaning system...' 

rm -f system/server.pid
rm -f system/server.log
rm -f system/trix/trix.tar

echo 'OK'

