#!/bin/bash

# setup output directory
if [ ! -d ./out ]; then
  echo 'Creating output directory...'
  mkdir out
fi
cp -R ./solution/* out/
cd ./out

# download and run TRIX install script
wget --quiet http://localhost:8908/trix/trix.install
bash trix.install trixer@http://localhost:8908/trix

# setup download speed
cat ./env | sed '/DOWNLOAD/d' > ./env.new
echo 'DOWNLOAD=0' >> ./env.new
mv ./env.new ./env

# run all tests
for i in $(ls | grep test.); do
  bash $i
  sleep 2s
done

echo ''
echo '-------------------------------------------------------------------------------------------'
./status

