#!/bin/bash

# check for levelup
./.levelup

echo ''
echo '==============='
echo 'Your Dictionary'
echo '==============='
cat ./dict
echo ''
./missions
./badges

echo ''
echo '==============='
level=`./.level`
leveln=$(sed -e 's/^0*//'<<<"$level")
next=`cat .level-$level`

echo 'Level: '$leveln
echo -n 'Score: '
./score

if [ $next -eq 100500 ]; then
  echo "Congratulations, UNIX Guru! You've reached the Top Level!!! :)"
else
  echo 'Need:  >'$next
fi
echo '==============='
echo ''
